{
 "title": "Pizza Dashboard",
 "description": "simple logs for JWT pizza. Will be updated with more logging information over time.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Revenue/minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(money_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "users_ratio{users=\"active_users\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Pizza Purchases/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(pizza_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_percent{system=\"RAM\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_percent{system=\"CPU\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sum(rate(requests_total[1m]))", "legendFormat": "ALL" },
    { "expr": "rate(requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication Attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "rate(users_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_milliseconds_total{latency=\"latency\"}",
     "legendFormat": "site latency"
    }
   ]
  },
  {
   "title": "Instantaneous Pizza Factory Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_milliseconds_total{latency=\"latencyFactory\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}